<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="parcours" nsURI="http://www.lpdql.org/parcours/0.1" nsPrefix="parcours">
  <eClassifiers xsi:type="ecore:EClass" name="Carte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="point1" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="point2" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temps" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parcours" interface="true">
    <eOperations name="calculDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="calculTemps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="calculRoutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParcoursRapide" eSuperTypes="#//Parcours"/>
</ecore:EPackage>
